version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            sudo apt-get install python-dev python-pip -qy
            pip install -r requirements.txt -t .

      - run: 
          name: Set Token in serverless config
          command: sed -i.bak -E "s!YOUR_ROOKOUT_TOKEN!$DEMO_ROOKOUT_TOKEN!g" serverless.yml

      - run:
          name: Deploy application
          command: sls deploy